[tool.poetry]
name = "ml-pipeline"
version = "0.1.0"
description = ""
authors = ["Marco <m.marthe@enlite.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
